server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/lunelio;
    index index.html;
    gzip on;
    gzip_types text/html;

    # le dossier .git ne doit jamais être servi
    location ~ /\. { deny all; }
    # les sources ne sont pas utiles au navigateur
    location /src/ { deny all; }
    location /deploy/ { deny all; }

    location / {
        try_files $uri $uri/ =404;
        add_header Cache-Control "no-cache";
    }
}
